
package mypackage;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserAuthService", targetNamespace = "http://services.ws.common.idm.yonyou/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserAuthService {


    /**
     * 
     * @param reqxml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "generateUserToke")
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "generateUserToke", targetNamespace = "http://services.ws.common.idm.yonyou/", className = "mypackage.GenerateUserToke")
    @ResponseWrapper(localName = "generateUserTokeResponse", targetNamespace = "http://services.ws.common.idm.yonyou/", className = "mypackage.GenerateUserTokeResponse")
    public String generateUserToke(
        @WebParam(name = "reqxml", targetNamespace = "")
        String reqxml);

    /**
     * 
     * @param reqxml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "checkClientUserAccessPermission")
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "checkClientUserAccessPermission", targetNamespace = "http://services.ws.common.idm.yonyou/", className = "mypackage.CheckClientUserAccessPermission")
    @ResponseWrapper(localName = "checkClientUserAccessPermissionResponse", targetNamespace = "http://services.ws.common.idm.yonyou/", className = "mypackage.CheckClientUserAccessPermissionResponse")
    public String checkClientUserAccessPermission(
        @WebParam(name = "reqxml", targetNamespace = "")
        String reqxml);

    /**
     * 
     * @param reqxml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "userAuthLog")
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "userAuthLog", targetNamespace = "http://services.ws.common.idm.yonyou/", className = "mypackage.UserAuthLog")
    @ResponseWrapper(localName = "userAuthLogResponse", targetNamespace = "http://services.ws.common.idm.yonyou/", className = "mypackage.UserAuthLogResponse")
    public String userAuthLog(
        @WebParam(name = "reqxml", targetNamespace = "")
        String reqxml);

    /**
     * 
     * @param userInfoXML
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "verifyUserLogin")
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "verifyUserLogin", targetNamespace = "http://services.ws.common.idm.yonyou/", className = "mypackage.VerifyUserLogin")
    @ResponseWrapper(localName = "verifyUserLoginResponse", targetNamespace = "http://services.ws.common.idm.yonyou/", className = "mypackage.VerifyUserLoginResponse")
    public String verifyUserLogin(
        @WebParam(name = "userInfoXML", targetNamespace = "")
        String userInfoXML);

    /**
     * 
     * @param reqxml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "validUserToke")
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "validUserToke", targetNamespace = "http://services.ws.common.idm.yonyou/", className = "mypackage.ValidUserToke")
    @ResponseWrapper(localName = "validUserTokeResponse", targetNamespace = "http://services.ws.common.idm.yonyou/", className = "mypackage.ValidUserTokeResponse")
    public String validUserToke(
        @WebParam(name = "reqxml", targetNamespace = "")
        String reqxml);

    /**
     * 
     * @param password
     * @param userName
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "verifyUserAndPass")
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "verifyUserAndPass", targetNamespace = "http://services.ws.common.idm.yonyou/", className = "mypackage.VerifyUserAndPass")
    @ResponseWrapper(localName = "verifyUserAndPassResponse", targetNamespace = "http://services.ws.common.idm.yonyou/", className = "mypackage.VerifyUserAndPassResponse")
    public String verifyUserAndPass(
        @WebParam(name = "userName", targetNamespace = "")
        String userName,
        @WebParam(name = "password", targetNamespace = "")
        String password);

}
